---
engine: knitr
editor_options: 
  chunk_output_type: console
---

# RNA sample selection


```{r}
library(tidyverse)
library(patchwork)
library(prismatic)
set.seed(22)
clr1 <-  "gray20";  clr2 <-  "gray50"
clrs <- c( clr_darken("#db4a32",.3),
           clr_darken("#66c2a5",.3))

data <- read_tsv(here::here("data/rna/multiqc_general_stats.txt")) |> 
  filter(Sample != "multiqc") |> 
  rename_with(\(x){str_remove_all(x, "FastQC_mqc-generalstats-fastqc-|Snippy_mqc-generalstats-snippy-")}) |> 
  mutate(pair = str_sub(Sample, 1,-3),
         mate = str_sub(Sample, -1,-1)) |> 
  select(-Sample) |> 
  pivot_wider(names_from = mate,id_cols = pair, values_from = percent_duplicates:total_sequences) |> 
  mutate(pair = fct_reorder(pair, total_sequences_1)) |> 
  arrange(total_sequences_1) |> 
  separate(pair, into = c("sample_id", "beach", "stage", "timepoint", "year"),
           sep = "_",remove = FALSE)

selected_pairs <- data |> 
  filter(!is.na(stage)) |> 
  group_by(beach, stage, .drop = FALSE) |>
  sample_n(size = 5) |>
  filter(!(stage == "pup" & beach == "FWB" & row_number() == 5)) |>
  pluck('pair')

data <- data |> 
  mutate(select = pair %in% selected_pairs)
```

Checking the total number of sequences selected (at `select` is `TRUE`)

```{r}
# The upper limit is 600M pairs of reads to avoi
data |> 
  group_by(select) |> 
  summarise(n_seqs = sum(total_sequences_1) * 1e-6)
```

Checking selection across different beaches and age classes

```{r}
data |> 
  group_by(select, beach, stage, .drop = FALSE) |> 
  summarise(n_seqs = sum(total_sequences_1) * 1e-6,
            n = n(), .drop = FALSE)
```

Visual check:

```{r}
#| fig-width: 12
#| fig-height: 13
p1 <- data |> 
  ggplot() +
  ggstance::geom_barh(aes(y = pair, x = total_sequences_1 * 1e-6,
                          color = select, fill = after_scale(clr_alpha(color))),
                      stat = 'identity', linewidth= .5, show.legend =  'none')+
  labs(x = "number of sequences (Mil)") +
  coord_cartesian(xlim = c(0, 70))

p2 <- data |> 
  # names()
  ggplot(aes(x = total_sequences_1 * 1e-6,  color = select)) +
  geom_histogram(linewidth= .5,bins = 17, 
                 aes(group = select, fill = after_scale(clr_alpha(color))),
                 show.legend =  'none') +
  labs(x = "number of sequences (Mil)") +
  coord_cartesian(xlim = c(0, 70))

p2 / p1 + plot_layout(heights = c(.3, 1)) & scale_color_manual(values = clrs, guide = "none") & theme_minimal() 
```

Selected Individuals

```{r}
data |>
  filter(select) |>
  select(pair:year, total_sequences_1) |> 
  arrange(beach, stage, timepoint) |> 
  knitr::kable()

```

