ref: arcgaz_dt_h1

queries:
  - arcgaz_dt_h2
  - arcgaz_anc_h1
  - arcgaz_anc_h2
  - arcgaz_v3
  - arcgaz_v1_2
  - arcgaz_v1_4
  - zalcal_v1

lastParams: "-m 1 -j 3 -u 1 -p HOXD70"
# lastParams: "-j 3"

genomes:
  - arcgaz_dt_h1
  - arcgaz_dt_h2
  - arcgaz_v3
  - arcgaz_v1_2
  - arcgaz_v1_4
  - zalcal_v1

haplotypes:
  - h1
  - h2

mask_suffix: '_hardmasked'

# cactus section
singularity_bind_paths: '$(pwd),$CDATA'
# --------------
alignment_name: 'pinniped_set'
refName: arcgaz

species:
  - calurs
  - eumjub
  - halgry
  - lepwed
  - mirang
  - mirleo
  - neosch
  - odoros
  - phovit
  - zalcal

speciesTree: "((odoros,(calurs,(arcgaz,(eumjub,zalcal)))),(((lepwed,(mirleo,mirang)),neosch),(phovit,halgry)));"

# technical parameters
# cactus_sif:
# apptainer pull docker://quay.io/comparative-genomics-toolkit/cactus:v2.5.1
cactus_sif: '$CDATA/apptainer_local/cactus_v2.5.1.sif'
# cactus_sif: 'docker://quay.io/comparative-genomics-toolkit/cactus:v2.5.1'
cactus_cores: "8"