ref: arcgaz_dt_h1

queries:
  - arcgaz_dt_h2
  - arcgaz_anc_h1
  - arcgaz_anc_h2
  - arcgaz_v3
  - arcgaz_v1_2
  - arcgaz_v1_4
  - zalcal_v1

lastParams: "-m 1 -j 3 -u 1 -p HOXD70"
# lastParams: "-j 3"

genomes:
  - arcgaz_dt_h1
  - arcgaz_dt_h2
  - arcgaz_v3
  - arcgaz_v1_2
  - arcgaz_v1_4
  - zalcal_v1

haplotypes:
  - h1
  - h2

mask_suffix: '_hardmasked'