ref: arcgaz_dt_h1

queries:
  - arcgaz_dt_h2
  - arcgaz_v1
  - arcgaz_bp
  - zalcal_v1

lastParams: "-m 1 -j 3 -u 1 -p HOXD70"
# lastParams: "-j 3"

genomes:
  - arcgaz_dt_h1
  - arcgaz_dt_h2
  - arcgaz_v1
  - arcgaz_bp
  - zalcal_v1