project:
  type: book
  output-dir: docs/

engine: knitr

book:
  title: "arcgaz_genome"
  author: "David Vendrami and Kosmas Hench"
  date: "2022-11-16"
  chapters:
    - index.qmd
    - qmd/initial_genome_check.qmd
    - qmd/inspect_initial_alignments.qmd
    - qmd/anchoring_assessment.qmd
    - qmd/inspect_anchored_alignments.qmd
    - qmd/genome_stats.qmd
    - qmd/rna_sample_selection.qmd
    - qmd/references.qmd
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/k-hench/arcgaz_genome
bibliography: references.bib

from: markdown+emoji

format:
  html:
    theme:
    - simplex
    - styles.scss
    code-fold: true
    code-summary: "toggle code"
    mainfont: "'CMU Sans Serif', 'Open sans', sans"
    monofont: "'Fira Code', 'Ubuntu mono', monospace"
    fig-format: "svg"

execute:
  message: false
  warning: false

crossref:
  fig-title: Figure     # (default is "Figure")
  fig-prefix: Fig   # (default is "fig.")
  tbl-title: Table     # (default is "Table")
  tbl-prefix: Tab    # (default is "tbl.")
  eq-title: Equation     # (default is "Table")
  eq-prefix: eq    # (default is "tbl.")

highlight-style: printing # zenburn
